#!/usr/bin/bash

export PATH=$HOME/go/bin:$PATH

# =python

alias python=python3
alias pip=pip3
alias ipdb=ipdb3

export PYTHONBREAKPOINT=ipdb.set_trace

export ipython="$HOME/.ipython/profile_default/startup/"

# =bash

tabs -4

stty -ixon # disable xoff/xon signaling for ctrl+s

# =scheme

alias miti='racket -i -f '
alias mit='racket -f '

# =other

export EDITOR=micro

alias sudo='sudo '

export DOCKER_SCAN_SUGGEST=false

alias xl='exa --group-directories-first --classify --git'
alias xll='xl --long'

alias help=run-help
