#!/usr/bin/bash

# =python

alias python=python3
alias pip=pip3
alias ipdb=ipdb3

export PYTHONPATH="$HOME/playground/:$PYTHONPATH"
export PYTHONPATH="$HOME/playground/lib/:$PYTHONPATH"

export PYTHONBREAKPOINT=ipdb.set_trace

export ipython="$HOME/.ipython/profile_default/startup/"

# =bash

tabs 4

stty -ixon # disable xoff/xon signaling for ctrl+s

# =golang

export GOPATH="$HOME/opt/go/"
export PATH="$HOME/opt/go/bin/:$PATH"

# =scheme

alias miti='racket -i -f '
alias mit='racket -f '

# =sg

export svol="$HOME/samoletgroup/svolume/"

# =other

export EDITOR=micro

export sublime="$HOME/.config/sublime-text-3/Packages/"

export src="$HOME/src/"

alias sudo='sudo '
alias copy='xclip -sel clip'

export KUBECONFIG=$HOME/.kube/config
