#!/usr/bin/bash

export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/go/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.krew//bin:$PATH

# =python

alias python=python3
alias pip=pip3
alias ipdb=ipdb3

export PYTHONBREAKPOINT=ipdb.set_trace

export ipython="$HOME/.ipython/profile_default/startup/"

export PIP_DISABLE_PIP_VERSION_CHECK=1

# =bash

tabs -4

stty -ixon # disable xoff/xon signaling for ctrl+s

# =scheme

alias miti='racket -i -f '
alias mit='racket -f '

# =docker

if command -v colima &> /dev/null; then
    export DOCKER_HOST="unix://${HOME}/.colima/default/docker.sock"
fi

# =other

export EDITOR=micro
export BAT_THEME='Monokai Extended'

alias sudo='sudo '

alias xl='exa --group-directories-first --classify --git'
alias xll='xl --long'

alias help=run-help

alias idea='open -a "IntelliJ IDEA.app"'
alias idean='open -na "IntelliJ IDEA.app" --args'

export HOMEBREW_NO_AUTO_UPDATE=0
export HOMEBREW_NO_ANALYTICS=1

export FZF_DEFAULT_OPTS='--multi'
