name: Lint Markdown

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Lint text action
      uses: bravmi/lint-text-action@master
      with:
        tool: 'proselint'  # Change to 'write-good' if preferred
