name: Lint Markdown

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint text action
        id: lint
        uses: bravmi/lint-text-action@master
        with:
          tool: 'proselint'  # Change to 'write-good' if preferred

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}

