name: Lint Markdown

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint text action
        id: lint
        uses: bravmi/lint-text-action@master
        with:
          tool: 'proselint'  # Change to 'write-good' if preferred
          ignore_paths: "zsh"

      - name: Show lint results
        run: |
          ls -l /github/workspace
          echo ${{ github.workspace }}
          ls -l ${{ github.workspace }}
          cat /github/workspace/lint.log
